import pyarrow as pa

schema_nota = pa.schema(  
    [
        pa.field("controle", pa.string()),
        pa.field("status", pa.int8()),
        pa.field("chave", pa.string()),
        pa.field("dh_emi", pa.timestamp("us")),
        pa.field("cnpj_origem", pa.string()),
        pa.field("cnpj_destino", pa.string()),
        pa.field("natureza_operacao", pa.string()),
        pa.field("numero_nota", pa.int64()),
        pa.field("valor_nota", pa.float64()),
        pa.field("valor_prod", pa.float64()),
        pa.field("valor_desc", pa.float64()),
        pa.field("valor_base_calculo", pa.float64()),
        pa.field("valor_icms", pa.float64()),
        pa.field("valor_ipi", pa.float64()),
        pa.field("valor_pis", pa.float64()),
        pa.field("valor_cofins", pa.float64()),
        pa.field("serie", pa.int16()),
        pa.field("ref_chave", pa.string()),
        pa.field("item", pa.int16()),
        pa.field("cod", pa.int32()),
        pa.field("cod_barra", pa.string()),
        pa.field("nome_prod", pa.string()),
        pa.field("ncm", pa.string()),
        pa.field("cfop", pa.int32()),
        pa.field("und_comercial", pa.string()),
        pa.field("qtd", pa.int64()),
        pa.field("vl_unit", pa.float64()),
        pa.field("vl_desc", pa.float64()),
        pa.field("vl_prod", pa.float64()),
        pa.field("vl_base_icms", pa.float64()),
        pa.field("perc_icms", pa.float64()),
        pa.field("vl_icms", pa.float64()),
        pa.field("vl_base_ipi", pa.float64()),
        pa.field("perc_ipi", pa.float64()),
        pa.field("vl_ipi", pa.float64()),
        pa.field("vl_base_pis", pa.float64()),
        pa.field("perc_pis", pa.float64()),
        pa.field("vl_pis", pa.float64()),
        pa.field("vl_base_cofins", pa.float64()),
        pa.field("perc_cofins", pa.float64()),
        pa.field("vl_cofins", pa.float64()),
        pa.field("orig", pa.int32()),
        pa.field("lote", pa.string()),
        pa.field("qtd_lote", pa.int64()),
        pa.field("dt_fab", pa.timestamp("us")),
        pa.field("dt_val", pa.timestamp("us")),
    ]
)
